apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balances-watcher
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - balance-watcher.info
      secretName: balances-watcher-tls
  rules:
    - host: balance-watcher.info
      http:
        paths:
          - path: /1/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-eth
                port:
                  number: 80
          - path: /sse/1/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-eth
                port:
                  number: 80

          - path: /42161/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-arb
                port:
                  number: 80
          - path: /sse/42161/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-arb
                port:
                  number: 80

          # - path: /100/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: balances-watcher-gnosis
          #       port:
          #         number: 80
          # - path: /sse/100/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: balances-watcher-gnosis
          #       port:
          #         number: 80

          - path: /11155111/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-sepolia
                port:
                  number: 80
          - path: /sse/11155111/
            pathType: Prefix
            backend:
              service:
                name: balances-watcher-sepolia
                port:
                  number: 80
